debug: true # Show extra information in the console

mainCommandName: 'myplugin' # Name of the main command of the plugin
mainCommandAliases: ['mp'] # Aliases for the main command
guiCommandName: 'menu' # Name of the command to open the GUI
guiCommandAliases: ['gui', 'g'] # Aliases for the menu command